# Generated by Django 3.0.8 on 2020-07-21 21:27

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=500)),
                ('information', markdownx.models.MarkdownxField()),
                ('capacity', models.SmallIntegerField()),
                ('poster', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('major', models.CharField(choices=[('IS', 'Ingeniería de Sistemas'), ('IE', 'Ingeniería Electrónica'), ('II', 'Ingeniería Industrial'), ('IC', 'Ingeniería Civil'), ('MT', 'Matemáticas'), ('OT', 'Otro')], max_length=50)),
                ('identification', models.CharField(max_length=50, null=True)),
                ('date_major', models.DateField(null=True)),
                ('date_chapter', models.DateField(null=True)),
                ('date_birth', models.DateField(null=True)),
                ('cellphone', models.CharField(max_length=20, null=True)),
                ('picture', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('1PRE', 'Presidente'), ('2VIC', 'Vice-Presidente'), ('3SEC', 'Secretario'), ('4TES', 'Tesorero'), ('5CM', 'Comunity Manager'), ('6ME', 'Miembro')], max_length=5, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('reason', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('information', markdownx.models.MarkdownxField()),
                ('poster', models.CharField(max_length=200)),
                ('gallery', models.ManyToManyField(blank=True, related_name='tutorials', to='activities.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('information', markdownx.models.MarkdownxField()),
                ('poster', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('gallery', models.ManyToManyField(blank=True, related_name='projects', to='activities.Gallery')),
                ('members', models.ManyToManyField(related_name='projects', to='activities.Member')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ENC', 'Encargado'), ('AYU', 'Ayudante'), ('PAR', 'Participante')], max_length=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Member')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.Gallery'),
        ),
        migrations.AddField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(related_name='activities', through='activities.ActivityMember', to='activities.Member'),
        ),
    ]
