# Generated by Django 2.0.1 on 2021-01-02 21:29

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=500)),
                ('information', markdownx.models.MarkdownxField()),
                ('capacity', models.SmallIntegerField()),
                ('poster', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ENC', 'Encargado'), ('AYU', 'Ayudante'), ('PAR', 'Participante')], max_length=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('information', markdownx.models.MarkdownxField()),
                ('poster', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('gallery', models.ManyToManyField(blank=True, related_name='projects', to='activities.Gallery')),
                ('members', models.ManyToManyField(related_name='projects', to='people.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('information', markdownx.models.MarkdownxField()),
                ('poster', models.CharField(max_length=200)),
                ('gallery', models.ManyToManyField(blank=True, related_name='tutorials', to='activities.Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='activityattendee',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Attendee'),
        ),
        migrations.AddField(
            model_name='activity',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.Gallery'),
        ),
        migrations.AddField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(related_name='activities', through='activities.ActivityMember', to='people.Member'),
        ),
    ]
