# Generated by Django 2.0.1 on 2020-07-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('activities', '0003_attendee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Member')),
            ],
        ),
    ]
