# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ENC', 'Encargado'), ('AYU', 'Ayudante'), ('PAR', 'Participante')], max_length=10)),
                ('idActivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('NAC', 'Maratón Nacional'), ('REG', 'Maratón Regional'), ('MUN', 'Maratón Mundial')], max_length=10)),
                ('date', models.DateField()),
                ('place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('ext', models.CharField(choices=[('img', 'Image'), ('md', 'Markdown'), ('mdf', 'MarkdownForm'), ('json', 'JSON'), ('ot', 'Other')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('major', models.CharField(max_length=200)),
                ('identification', models.CharField(max_length=50)),
                ('dateMajor', models.DateField()),
                ('dateChapter', models.DateField()),
                ('dateBirth', models.DateField()),
                ('cellphone', models.CharField(max_length=20)),
                ('idPhoto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebSite.File')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStart', models.DateField()),
                ('dateEnd', models.DateField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.File')),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Member')),
                ('idProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('idFile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebSite.File')),
            ],
        ),
        migrations.CreateModel(
            name='TeamContest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Contest')),
                ('idTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('idMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Member')),
                ('idTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.File')),
                ('idTutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Tutorial')),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='idFile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='WebSite.File'),
        ),
        migrations.AddField(
            model_name='activitymember',
            name='idMember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.Member'),
        ),
        migrations.AddField(
            model_name='activityfile',
            name='idFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.File'),
        ),
    ]
