# Generated by Django 2.0.1 on 2018-01-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_member_descrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('1PRE', 'Presidente'), ('2VIC', 'Vice-Presidente'), ('3SEC', 'Secretario'), ('4TES', 'Tesorero'), ('5CM', 'Comunity Manager')], max_length=5, null=True),
        ),
    ]
