# Generated by Django 2.0.1 on 2018-01-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0003_auto_20180117_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='descrition',
            new_name='description',
        ),
    ]
