# Generated by Django 2.0.1 on 2020-07-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='team',
        ),
        migrations.AlterField(
            model_name='activity',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='activities', to='web_site.Gallery'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='members',
            field=models.ManyToManyField(related_name='activities', through='web_site.ActivityMember', to='people.Member'),
        ),
        migrations.AlterField(
            model_name='activitymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Member'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='teams',
            field=models.ManyToManyField(related_name='contests', to='people.Team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='projects', to='web_site.Gallery'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', to='people.Member'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='tutorials', to='web_site.Gallery'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
