# Generated by Django 3.1.12 on 2021-09-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('1PRE', 'Presidente'), ('2VIC', 'Vice-Presidente'), ('3LCC', 'Lider Curso de Colegios'), ('4LDW', 'Lider Desarrollo Web'), ('5SEC', 'Secretario'), ('6TES', 'Tesorero'), ('7CM', 'Community Manager'), ('8STF', 'Staff'), ('6ME', 'Miembro')], max_length=5, null=True),
        ),
    ]
