# Generated by Django 3.0.3 on 2020-02-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='activities', to='WebSite.Gallery'),
        ),
        migrations.AlterField(
            model_name='project',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='projects', to='WebSite.Gallery'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='tutorials', to='WebSite.Gallery'),
        ),
    ]
